steps:
  # Step 1: Set up Maven and Build application
  - name: 'gcr.io/cloud-builders/mvn'
    args:
      - 'clean'
      - 'package'
      - '-DskipTests=true'

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/bulletin-board-repository/bulletin-board:$SHORT_SHA'
      - '.'

  # Step 3: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/bulletin-board-repository/bulletin-board:$SHORT_SHA'

  # Step 4: Add envsubst
  - name: 'gcr.io/$PROJECT_ID/envsubst'
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'SHORT_SHA=$SHORT_SHA'
    args: ['k8s/bulletin-board-deployment.yaml']

  # Step 5: Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=bulletin-board-cluster'
    args:
      - 'apply'
      - '-f'
      - 'k8s/'

options:
  logging: CLOUD_LOGGING_ONLY