steps:
  # Step 1: Build the Application
  - name: 'maven:3-eclipse-temurin-17-alpine'
    id: 'Build application'
    entrypoint: 'mvn'
    args: [ "package", "-Dmaven.test.skip=true" ]

  # Step 2: Build the Docker image for the Go application
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/my-repository/bulletin-board:v1.0', '.']


  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image'
    args: ['push', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/my-repository/bulletin-board:v1.0']

  # Step 4: Apply the deployment YAML file
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy'
    args: ['apply', '-f', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-asia-southeast2-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=bulletin-board-cluster'
options:
  logging: CLOUD_LOGGING_ONLY
