steps:
  # Step 1: Set up Maven and Build application
  - name: 'gcr.io/cloud-builders/mvn'
    args:
      - 'clean'
      - 'package'
      - '-DskipTests=true'

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/$REPO_DOCKER/bulletin-board:v1.0'
      - '.'

  # Step 3: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/$REPO_DOCKER/bulletin-board:v1.0'

  # Step 4: Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$CLUSTER_NAME'
    args:
      - 'apply'
      - '-f'
      - 'k8s/'

images:
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/$REPO_DOCKER/bulletin-board:v1.0'
